INSERT INTO PRODUCT (id, DELETED, CREATED_AT, MODIFIED_AT, LABEL, PRICE)
    VALUES (1, 0, NOW(), null, 'notDelete1', 2000);
INSERT INTO PRODUCT (id, DELETED, CREATED_AT, MODIFIED_AT, LABEL, PRICE)
    VALUES (2, 0, NOW(), null, 'notDelete2', 2000);
INSERT INTO PRODUCT (id, DELETED, CREATED_AT, MODIFIED_AT, LABEL, PRICE)
    VALUES (3, 0, NOW(), null, 'notDelete3', 2000);
INSERT INTO PRODUCT (id, DELETED, CREATED_AT, MODIFIED_AT, LABEL, PRICE)
    VALUES (4, 0, NOW(), null, 'notDelete4', 2000);


INSERT INTO MEMBER (id, DELETED, CREATED_AT, MODIFIED_AT, EMAIL, PASSWORD, ROLE)
    VALUES (1, 0, NOW(), null, 'label1', 'test1@sdfadfa.com', 'USER');
INSERT INTO MEMBER (id, DELETED, CREATED_AT, MODIFIED_AT, EMAIL, PASSWORD, ROLE)
    VALUES (2, 0, NOW(), null, 'label2', 'test2@sdfadfa.com', 'USER');
INSERT INTO MEMBER (id, DELETED, CREATED_AT, MODIFIED_AT, EMAIL, PASSWORD, ROLE)
    VALUES (3, 0, NOW(), null, 'label3', 'test3@sdfadfa.com', 'USER');
INSERT INTO MEMBER (id, DELETED, CREATED_AT, MODIFIED_AT, EMAIL, PASSWORD, ROLE)
    VALUES (4, 0, NOW(), null, 'label4', 'test4@sdfadfa.com', 'USER');